ApplyPromoCodeToCartInputDecorator:
    type: input-object
    decorator: true
    config:
        validation:
            -   Shopsys\FrontendApiBundle\Component\Constraints\PromoCode: ~
        fields:
            cartUuid:
                type: "Uuid"
                defaultValue: null
                description: "Cart identifier or null if customer is logged in"
            promoCode:
                type: "String!"
                description: "Promo code to be used after checkout"
