OrderFilterInputDecorator:
    type: input-object
    decorator: true
    config:
        description: "Filter orders"
        fields:
           createdAfter:
               type: "DateTime"
               description: "Filter orders created after this date"
           status:
               type: "OrderStatusEnum"
               description: "Filter orders created after this date"
