PasswordDecorator:
    type: custom-scalar
    config:
        description: "Represents and encapsulates a string for password"
        serialize: ["Shopsys\\FrontendApiBundle\\Model\\ScalarType\\PasswordType", "serialize"]
        parseValue: ["Shopsys\\FrontendApiBundle\\Model\\ScalarType\\PasswordType", "parseValue"]
        parseLiteral: ["Shopsys\\FrontendApiBundle\\Model\\ScalarType\\PasswordType", "parseLiteral"]
