AdvertImageDecorator:
    type: object
    decorator: true
    inherits:
        - 'Advert'
    config:
        fields:
            link:
                type: "String"
                description: "Advert link"
            images:
                type: "[Image!]!"
                description: "Advert images"
                resolve: '@=query("imagesByAdvertQuery", value, args["type"])'
                args:
                    type:
                        type: "String"
                        defaultValue: null
        interfaces:
            - 'Advert'
