AdvertImageDecorator:
    type: object
    decorator: true
    inherits:
        - 'Advert'
    config:
        fields:
            link:
                type: "String"
                description: "Advert link"
            images:
                type: "[Image!]!"
                description: "Advert image"
                resolve: '@=query("imagesByAdvertQuery", value, args["type"], args["size"])'
                args:
                    type:
                        type: "String"
                        defaultValue: null
                    size:
                        type: "String"
                        defaultValue: null
        interfaces:
            - 'Advert'
