BlogArticleDecorator:
    type: object
    decorator: true
    config:
        interfaces:
            - 'Breadcrumb'
            - 'Slug'
            - 'ArticleInterface'
            - 'Hreflang'
        fields:
            id:
                type: "Int!"
                description: "ID of category"
            uuid:
                type: "Uuid!"
                description: "The blog article UUID"
            name:
                type: "String!"
                description: "The blog article title"
            text:
                type: "String"
                description: "The blog article text"
            createdAt:
                type: "DateTime!"
                description: "Date and time of the blog article creation"
            visibleOnHomepage:
                type: "Boolean!"
                description: "Indicates whether the blog article is displayed on homepage"
            publishDate:
                type: "DateTime!"
                description: "Date and time of the blog article publishing"
            perex:
                type: "String"
                description: "The blog article perex"
            seoTitle:
                type: "String"
                description: "The blog article SEO title"
            seoMetaDescription:
                type: "String"
                description: "The blog article SEO meta description"
            seoH1:
                type: "String"
                description: "The blog article SEO H1 heading"
            blogCategories:
                type: "[BlogCategory!]!"
                description: "The list of the blog article blog categories"
            mainBlogCategoryUuid:
                type: "Uuid!"
                description: "The UUID of the main blog category of the blog article"
            link:
                type: "String!"
                description: "The blog article absolute URL"
            slug:
                type: "String!"
                description: "The blog article URL slug"
            breadcrumb:
                type: "[Link!]!"
                description: "Hierarchy of the current element in relation to the structure"
            images:
                type: "[Image!]!"
                description: "Blog article images"
                resolve: '@=query("imagesByBlogArticlePromiseQuery", value, args["type"])'
                args:
                    type:
                        type: "String"
                        defaultValue: null
            mainImage:
                type: "Image"
                description: "Blog article image by params"
                resolve: '@=query("mainImageByBlogArticlePromiseQuery", value, args["type"])'
                args:
                    type:
                        type: "String"
                        defaultValue: null
            hreflangLinks:
                type: "[HreflangLink!]!"
                description: "Alternate links for hreflang meta tags"
