BrandDecorator:
    type: object
    decorator: true
    config:
        description: "Represents a brand"
        fields:
            uuid:
                type: "Uuid!"
                description: "UUID"
            name:
                type: "String!"
                description: "Brand name"
            description:
                type: "String"
                description: "Brand description"
            link:
                type: "String!"
                description: "Brand main URL"
            seoTitle:
                type: "String"
                description: "Brand SEO title"
            seoMetaDescription:
                type: "String"
                description: "Brand SEO meta description"
            seoH1:
                type: "String"
                description: "Brand SEO H1"
            images:
                type: "[Image!]!"
                description: "Brand images"
                resolve: '@=query("imagesByEntityQuery", value, args["type"])'
                args:
                    type:
                        type: "String"
                        defaultValue: null
            products:
                type: "ProductConnection"
                description: "Paginated and ordered products of brand"
                argsBuilder:
                    builder: "PaginatorArgumentsBuilder"
                    config:
                        orderingModeType: 'ProductOrderingModeEnum'
                resolve: '@=query("productsByBrandQuery", args, value)'
