FlagDecorator:
    type: object
    decorator: true
    config:
        description: "Represents a flag"
        fields:
            uuid:
                type: "Uuid!"
                description: "UUID"
            name:
                type: "String"
                description: "Localized flag name (domain dependent)"
            rgbColor:
                type: "String"
                description: "Flag color in rgb format"
