ImageDecorator:
    type: object
    decorator: true
    config:
        description: "Represents an image"
        fields:
            name:
                type: "String"
                description: "Name of the image usable as an alternative text"
            url:
                type: "String!"
                description: "URL address of the image"
