LoginInputDecorator:
    type: input-object
    decorator: true
    config:
        fields:
            email:
                type: "String!"
                description: "The user email."
            password:
                type: "Password!"
                description: "The user password."
            productListsUuids:
                type: "[Uuid!]!"
                description: "Uuids of product lists that should be merged to the product lists of the user"
                defaultValue: []
