MainVariantDecorator:
    type: object
    decorator: true
    inherits:
        - 'ProductDecorator'
    config:
        fields:
            variants:
                type: '[Variant!]!'
        interfaces:
            - 'Product'
