MutationDecorator:
    type: object
    decorator: true
    config:
        fields:
            Login:
                type: Token!
                description: "Allow to log in as user"
                args:
                    input:
                        type: LoginInput!
                resolve: "@=mutation('user_login', [args])"
            RefreshTokens:
                type: Token!
                description: "Refresh access and refresh tokens"
                args:
                    input:
                        type: RefreshTokenInput!
                resolve: "@=mutation('refresh_tokens', [args])"
