OpeningHoursOfDayDecorator:
    type: object
    decorator: true
    config:
        description: "Represents store opening hours for a specific day"
        fields:
            date:
                type: "DateTime!"
                description: "Date of day with display timezone for domain"
            dayOfWeek:
                type: "Int!"
                description: "Day of the week"
            openingHoursRanges:
                type: "[OpeningHoursRange!]!"
                description: "An array of opening hours ranges (each range contains opening and closing time)"
