PaymentStatusDecorator:
    type: object
    decorator: true
    config:
        fields:
            isPaid:
                type: "Boolean!"
                description: "Whether the order is already paid or not"
            transactionCount:
                type: "Int!"
                description: "Count of already processed transactions"
            paymentType:
                type: "String!"
                description: "Type of payment"
