QueryDecorator:
    type: object
    decorator: true
    config:
        fields:
            categories:
                type: '[Category!]!'
                resolve: "@=resolver('categories')"
            products:
                type: "ProductConnection"
                argsBuilder: "Relay::Connection"
                resolve: "@=resolver('products', [args])"
            product:
                type: 'Product'
                resolve: "@=resolver('product', [args['uuid']])"
                args:
                    uuid:
                        type: "Uuid!"
            RegularProduct:
                type: 'RegularProduct'
            category:
                type: 'Category'
                resolve: "@=resolver('category', [args['uuid']])"
                args:
                    uuid:
                        type: "Uuid!"
            payments:
                type: '[Payment!]!'
                resolve: "@=resolver('payments')"
            payment:
                type: 'Payment'
                resolve: "@=resolver('payment', [args['uuid']])"
                args:
                    uuid:
                        type: "Uuid!"
            transports:
                type: '[Transport!]!'
                resolve: "@=resolver('transports')"
            transport:
                type: 'Transport'
                resolve: "@=resolver('transport', [args['uuid']])"
                args:
                    uuid:
                        type: "Uuid!"
