SettingsDecorator:
    type: object
    decorator: true
    config:
        description: "Represents settings of the current domain"
        fields:
            seo:
                type: "SeoSetting!"
                resolve: "@=query('seoSettingsQuery')"
                description: "Settings related to SEO"
            maxAllowedPaymentTransactions:
                type: Int!
                resolve: "@=query('maxAllowedPaymentTransactionsQuery')"
                description: "Max allowed payment transactions (how many times is user allowed to try the same payment)"
            pricing:
                type: "PricingSetting!"
                resolve: "@=query('pricingSettingsQuery')"
                description: "Settings related to pricing"
            contactFormMainText:
                type: String!
                resolve: "@=query('contactFormMainTextQuery')"
                description: "Main text for contact form"
