TransportDecorator:
    type: interface
    decorator: true
    config:
        description: "Represents a transport"
        fields:
            uuid:
                type: "Uuid!"
                description: "UUID"
            name:
                type: "String!"
                description: "Transport name"
            description:
                type: "String"
                description: "Localized transport description (domain dependent)"
            instruction:
                type: "String"
                description: "Localized transport instruction (domain dependent)"
            position:
                type: "Int!"
                description: "Transport position"
            price:
                type: "Price"
                description: "Transport price"
                resolve: '@=query("priceByTransportQuery", value)'
            images:
                type: "[Image]!"
                description: "Transport images"
                resolve: '@=query("imagesByEntityQuery", value, args["type"], args["size"])'
                args:
                    type:
                        type: "String"
                        defaultValue: null
                    size:
                        type: "String"
            payments:
                type: "[Payment!]!"
                description: "List of assigned payments"
