VariantDecorator:
    type: object
    decorator: true
    inherits:
        - 'ProductDecorator'
    config:
        fields:
            mainVariant:
                type: 'MainVariant'
        interfaces:
            - 'Product'
