OrderInputDecorator:
    type: input-object
    decorator: true
    config:
        description: "Represents the main input object to create orders"
        validation:
            -   Shopsys\FrontendApiBundle\Component\Constraints\ProductInOrder: ~
            -   Shopsys\FrontendApiBundle\Component\Constraints\TransportInOrder: ~
            -   Shopsys\FrontendApiBundle\Component\Constraints\PaymentInOrder: ~
            -   Shopsys\FrontendApiBundle\Component\Constraints\PaymentTransportRelation: ~
            -   Shopsys\FrontendApiBundle\Component\Constraints\DeliveryAddressUuid: ~
        fields:
            cartUuid:
                type: "Uuid"
                description: "Cart identifier used for getting carts of not logged customers"
                defaultValue: null
            firstName:
                type: "String!"
                description: "The customer's first name"
                validation:
                    -   NotBlank:
                            message: "Please enter first name"
                    -   Length:
                            max: 100
                            maxMessage: "First name cannot be longer than {{ limit }} characters"
            lastName:
                type: "String!"
                description: "The customer's last name"
                validation:
                    -   NotBlank:
                            message: "Please enter last name"
                    -   Length:
                            max: 100
                            maxMessage: "Last name cannot be longer than {{ limit }} characters"
            email:
                type: "String!"
                description: "The customer's email address"
                validation:
                    -   NotBlank:
                            message: "Please enter email"
                    -   Email:
                            message: "Please enter valid email"
                    -   Length:
                            max: 255
                            maxMessage: "Email cannot be longer than {{ limit }} characters"
            telephone:
                type: "String!"
                description: "The customer's phone number"
                validation:
                    -   NotBlank:
                            message: "Please enter telephone number"
                    -   Length:
                            max: 30
                            maxMessage: "Telephone number cannot be longer than {{ limit }} characters"

            onCompanyBehalf:
                type: "Boolean!"
                description: "Determines whether the order is made on the company behalf."
            companyName:
                type: "String"
                description: "The customer’s company name (required when onCompanyBehalf is true)"
                validation:
                    -   NotBlank:
                            message: "Please enter company name"
                            groups: "onCompanyBehalf"
                    -   Length:
                            max: 100
                            maxMessage: "Company name cannot be longer than {{ limit }} characters"
                            groups: "onCompanyBehalf"
            companyNumber:
                type: "String"
                description: "The customer’s company identification number (required when onCompanyBehalf is true)"
                validation:
                    -   NotBlank:
                            message: "Please enter identification number"
                            groups: "onCompanyBehalf"
                    -   Length:
                            max: 50
                            maxMessage: "Identification number cannot be longer than {{ limit }} characters"
                            groups: "onCompanyBehalf"
                    -   Regex:
                            pattern: '/^[0-9]+$/'
                            message: "Please fill in numbers only"
                            groups: "onCompanyBehalf"
            companyTaxNumber:
                type: "String"
                description: "The customer’s company tax number (required when onCompanyBehalf is true)"
                validation:
                    -   Length:
                            max: 50
                            maxMessage: "Tax number cannot be longer than {{ limit }} characters"
                            groups: "onCompanyBehalf"
                    -   Regex:
                            pattern: '/^[0-9A-Z]*([0-9]+[A-Z]+|[A-Z]+[0-9]+)[0-9A-Z]*$/'
                            message: "Please check Tax number format"
                            groups: "onCompanyBehalf"
            street:
                type: "String!"
                description: "Billing address street name (will be on the tax invoice)"
                validation:
                    -   NotBlank:
                            message: "Please enter street"
                    -   Length:
                            max: 100
                            maxMessage: "Street name cannot be longer than {{ limit }} characters"
            city:
                type: "String!"
                description: "Billing address city name (will be on the tax invoice)"
                validation:
                    -   NotBlank:
                            message: "Please enter city"
                    -   Length:
                            max: 100
                            maxMessage: "City name cannot be longer than {{ limit }} characters"

            postcode:
                type: "String!"
                description: "Billing address zip code (will be on the tax invoice)"
                validation:
                    -   NotBlank:
                            message: "Please enter zip code"
                    -   Length:
                            max: 30
                            maxMessage: "Zip code cannot be longer than {{ limit }} characters"

            country:
                type: "String!"
                description: "Billing address country code in ISO 3166-1 alpha-2 (Country will be on the tax invoice)"
                validation:
                    -   NotBlank:
                            message: "Please choose country"
                    -   \Shopsys\FrameworkBundle\Form\Constraints\Country: ~

            IsDeliveryAddressDifferentFromBilling:
                type: "Boolean!"
                description: "Determines whether to deliver products to a different address than the billing one"
            deliveryAddressUuid:
                type: "Uuid"
                description: "Delivery address identifier. Can be used by logged users only. If set, it takes precedence over the individual delivery address fields (deliveryFirstName, deliveryLastName, etc.)"
                defaultValue: null
            deliveryFirstName:
                type: "String"
                description: "First name of the contact person for delivery (required when IsDeliveryAddressDifferentFromBilling is true and deliveryAddressUuid is null)"
                validation:
                    -   NotBlank:
                            message: "Please enter first name of contact person"
                            groups: "IsDeliveryAddressDifferentFromBillingWithoutPreselected"
                    -   Length:
                            max: 100
                            maxMessage: "First name of contact person cannot be longer than {{ limit }} characters"
            deliveryLastName:
                type: "String"
                description: "Last name of the contact person for delivery (required when IsDeliveryAddressDifferentFromBilling is true and deliveryAddressUuid is null)"
                validation:
                    -   NotBlank:
                            message: "Please enter last name of contact person"
                            groups: "IsDeliveryAddressDifferentFromBillingWithoutPreselected"
                    -   Length:
                            max: 100
                            maxMessage: "Last name of contact person cannot be longer than {{ limit }} characters"
            deliveryCompanyName:
                type: "String"
                description: "Company name for delivery"
                validation:
                    -   Length:
                            max: 100
                            maxMessage: "Company name cannot be longer than {{ limit }} characters"
            deliveryTelephone:
                type: "String"
                description: "Contact telephone number for delivery"
                validation:
                    -   Length:
                            max: 30
                            maxMessage: "Telephone number cannot be longer than {{ limit }} characters"
            deliveryStreet:
                type: "String"
                description: "Street name for delivery (required when IsDeliveryAddressDifferentFromBilling is true and deliveryAddressUuid is null)"
                validation:
                    -   NotBlank:
                            message: "Please enter street"
                            groups: "IsDeliveryAddressDifferentFromBillingWithoutPreselected"
                    -   Length:
                            max: 100
                            maxMessage: "Street name cannot be longer than {{ limit }} characters"
            deliveryCity:
                type: "String"
                description: "City name for delivery (required when IsDeliveryAddressDifferentFromBilling is true and deliveryAddressUuid is null)"
                validation:
                    -   NotBlank:
                            message: "Please enter city"
                            groups: "IsDeliveryAddressDifferentFromBillingWithoutPreselected"
                    -   Length:
                            max: 100
                            maxMessage: "City name cannot be longer than {{ limit }} characters"
            deliveryPostcode:
                type: "String"
                description: "Zip code for delivery (required when IsDeliveryAddressDifferentFromBilling is true and deliveryAddressUuid is null)"
                validation:
                    -   NotBlank:
                            message: "Please enter zip code"
                            groups: "IsDeliveryAddressDifferentFromBillingWithoutPreselected"
                    -   Length:
                            max: 30
                            maxMessage: "Zip code cannot be longer than {{ limit }} characters"
            deliveryCountry:
                type: "String"
                description: "Country code in ISO 3166-1 alpha-2 for delivery (required when IsDeliveryAddressDifferentFromBilling is true and deliveryAddressUuid is null)"
                validation:
                    -   NotBlank:
                            message: "Please choose country"
                            groups: "IsDeliveryAddressDifferentFromBillingWithoutPreselected"
                    -   Shopsys\FrameworkBundle\Form\Constraints\Country:

            note:
                type: "String"
                description: "Other information related to the order"
            heurekaAgreement:
                type: "Boolean!"
                defaultValue: false
                description: "Determines whether the customer agrees with sending satisfaction questionnaires within the Verified by Customers Heureka program"
            newsletterSubscription:
                type: Boolean
                description: "Allows user to subscribe/unsubscribe newsletter."
                defaultValue: false
