EditCustomerUserPersonalDataInputDecorator:
    type: input-object
    inherits:
        - 'ChangePersonalDataInputDecorator'
        - 'TelephoneInputObjectDecorator'
    config:
        fields:
            customerUserUuid:
                type: "Uuid"
                description: "UUID"
                validation:
                    -   NotBlank:
                            message: "Please enter uuid"

            roleGroupUuid:
                type: "Uuid!"
                description: "Customer user role group uuid."
                validation:
                    -   Shopsys\FrontendApiBundle\Component\Constraints\CustomerUserRoleGroup:
                    -   Shopsys\FrontendApiBundle\Component\Constraints\CustomerUserRoleGroupAllowEdit:
