EditCustomerUserPersonalDataInputDecorator:
    type: input-object
    inherits:
        - 'ChangePersonalDataInputDecorator'
        - 'TelephoneInputObjectDecorator'
    config:
        fields:
            customerUserUuid:
                type: "Uuid"
                description: "UUID"
                validation:
                    -   NotBlank:
                            message: "Please enter uuid"

