RegistrationDataInputDecorator:
    type: input-object
    decorator: true
    inherits:
        - 'NameInputObjectDecorator'
        - 'TelephoneInputObjectDecorator'
        - 'BillingAddressInputObjectDecorator'
        - 'CompanyInputObjectDecorator'
    config:
        description: "Represents the main input object to register customer user"
        fields:
            email:
                type: "String!"
                description: "The customer's email address"
                validation:
                    -   NotBlank:
                            message: "Please enter email"
                    -   Email:
                            message: "Please enter valid email"
                    -   Length:
                            max: 255
                            maxMessage: "Email cannot be longer than {{ limit }} characters"
                    -   Shopsys\FrameworkBundle\Form\Constraints\UniqueEmail:
                            message: "This email is already registered"
            password:
                type: "Password!"
                description: "Customer user password"
                validation:
                    -   NotBlank:
                            message: "Please enter new password"
                    -   Length:
                            min: 6
                            minMessage: "Password must be at least {{ limit }} characters long"
            newsletterSubscription:
                type: "Boolean!"
                description: "Whether customer user should receive newsletters or not"
            cartUuid:
                type: "Uuid"
                description: "Uuid of the cart that should be merged to the cart of the newly registered user"
                defaultValue: null
            productListsUuids:
                type: "[Uuid!]!"
                description: "Uuids of product lists that should be merged to the product lists of the user after registration"
                defaultValue: []
