CartTransportModificationsResultDecorator:
    type: object
    decorator: true
    config:
        fields:
            transportPriceChanged:
                type: "Boolean!"
            transportUnavailable:
                type: "Boolean!"
            transportWeightLimitExceeded:
                type: "Boolean!"
            personalPickupStoreUnavailable:
                type: "Boolean!"
