CartPaymentModificationsResultDecorator:
    type: object
    decorator: true
    config:
        fields:
            paymentPriceChanged:
                type: "Boolean!"
            paymentUnavailable:
                type: "Boolean!"
