SalesRepresentativeDecorator:
    type: object
    decorator: true
    config:
        description: "Represents sales representative"
        fields:
            uuid:
                type: "Uuid!"
                description: "UUID"
            firstName:
                type: "String"
                description: "First name"
            lastName:
                type: "String"
                description: "Last name"
            email:
                type: "String"
                description: "Email address"
            telephone:
                type: "String"
                description: "Phone number"
            image:
                type: "Image"
                description: "Sales representative image"
                resolve: '@=query("imageBySalesRepresentativePromiseQuery", value, args["type"])'
                args:
                    type:
                        type: "String"
                        defaultValue: null