ProductListTypeEnumDecorator:
    type: enum
    decorator: true
    config:
        description: "One of possible types of the product list"
        values:
            WISHLIST:
                value: '@=constant("Shopsys\\FrameworkBundle\\Model\\Product\\List\\ProductListTypeEnum::WISHLIST")'
            COMPARISON:
                value: '@=constant("Shopsys\\FrameworkBundle\\Model\\Product\\List\\ProductListTypeEnum::COMPARISON")'
