overblog_graphiql_endpoint:
    defaults:
        _controller: Overblog\GraphiQLBundle\Controller\GraphiQLController::indexAction
    path: /graphiql/

overblog_graphiql_endpoint_multiple:
    defaults:
        _controller: Overblog\GraphiQLBundle\Controller\GraphiQLController::indexAction
    path: /graphiql/{schemaName}
