services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Shopsys\FrontendApiBundle\:
        resource: '../../**/*{Resolver}.php'

    shopsys.frontend_api.route_loader:
        public: true
        class: 'Shopsys\FrontendApiBundle\Routing\FrontendApiRouteLoader'
        arguments:
            $environment: '%kernel.environment%'
