MainVariantDecorator:
    type: object
    decorator: true
    inherits:
        - 'Product'
    config:
        fields:
            variantsCount:
                type: "Int!"
                description: "Number of sellable variants"
            variants:
                type: '[Variant!]!'
        interfaces:
            - 'Product'
            - 'Hreflang'
