CompanyInputObjectDecorator:
    type: input-object
    decorator: true
    config:
        validation:
            -   Shopsys\FrontendApiBundle\Component\Constraints\UniqueBillingAddressApi: ~
        fields:
            companyCustomer:
                type: "Boolean"
                defaultValue: false
                description: "Determines whether the customer is a company or not."
            companyName:
                type: "String"
                description: "The customer’s company name (required when companyCustomer is true)"
                validation:
                    -   NotBlank:
                            message: "Please enter company name"
                            groups: "companyCustomer"
                    -   Length:
                            max: 100
                            maxMessage: "Company name cannot be longer than {{ limit }} characters"
                            groups: "companyCustomer"
            companyNumber:
                type: "String"
                description: "The customer’s company identification number (required when companyCustomer is true)"
                validation:
                    -   NotBlank:
                            message: "Please enter identification number"
                            groups: "companyCustomer"
                    -   Length:
                            max: 50
                            maxMessage: "Identification number cannot be longer than {{ limit }} characters"
                            groups: "companyCustomer"
                    -   Regex:
                            pattern: '/^[0-9]+$/'
                            message: "Please fill in numbers only"
                            groups: "companyCustomer"
            companyTaxNumber:
                type: "String"
                description: "The customer’s company tax number (required when companyCustomer is true)"
                validation:
                    -   Length:
                            max: 50
                            maxMessage: "Tax number cannot be longer than {{ limit }} characters"
                            groups: "companyCustomer"
                    -   Regex:
                            pattern: '/^[0-9A-Z]*([0-9]+[A-Z]+|[A-Z]+[0-9]+)[0-9A-Z]*$/'
                            message: "Please check Tax number format"
                            groups: "companyCustomer"
