CreateOrderResultDecorator:
    type: object
    decorator: true
    config:
        fields:
            order:
                type: "Order"
            cart:
                type: "Cart"
            orderCreated:
                type: "Boolean!"
