OrderItemConnectionDecorator:
    type: object
    decorator: true
    config:
        fields:
            totalCount:
                type: "Int!"
                description: "Total number of order items"
