AddToCartResultDecorator:
    type: object
    decorator: true
    config:
        fields:
            addProductResult:
                type: "AddProductResult!"
            cart:
                type: "Cart!"
